name: Build and publish package

on:
  push:
    branches:
      - master

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Python
      - uses: actions/setup-python@v1
        with:
          python-version: 3.11

      # Set up Poetry
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      # Load cached dependencies
      - name: Load cached venv
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      # Install dependencies
      - if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: poetry install --without test,dev

      # Version package
      - run: poetry run semantic-release version

      # Configure basic credentials for PyPI
      - run: poetry config pypi-token.pypi "${{ secrets.PYPI_PASSWORD }}"

      # Build and publish package
      - run: poetry build
      - run: poetry publish
